import { Pet, Notification } from './types'

export const mockPets: Pet[] = [
  {
    id: '1',
    userId: '1',
    status: 'lost',
    name: 'Rex',
    type: 'dog',
    breed: 'Labrador',
    size: 'large',
    age: '3 anos',
    location: {
      lat: -23.5505,
      lng: -46.6333,
      address: 'Av. Paulista, 1000',
      city: 'São Paulo',
      neighborhood: 'Bela Vista',
    },
    lastSeenDate: new Date('2024-01-15'),
    description: 'Cachorro labrador dourado, muito amigável. Desapareceu com coleira vermelha.',
    photoUrl: '/golden-labrador-dog.jpg',
    reward: 500,
    contactPhone: '+5511987654321',
    contactName: 'João Silva',
    sightings: [
      {
        id: 's1',
        petId: '1',
        location: {
          lat: -23.5525,
          lng: -46.6350,
          address: 'Rua Augusta, 500',
          city: 'São Paulo',
          neighborhood: 'Consolação',
        },
        date: new Date('2024-01-16'),
        time: '14:30',
        description: 'Vi ele correndo perto do parque',
        reporterName: 'Maria Santos',
        reporterPhone: '+5511976543210',
        createdAt: new Date('2024-01-16'),
      },
    ],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    userId: '2',
    status: 'found',
    type: 'cat',
    breed: 'Siamês',
    size: 'small',
    location: {
      lat: -23.5615,
      lng: -46.6560,
      address: 'Rua da Consolação, 300',
      city: 'São Paulo',
      neighborhood: 'Consolação',
    },
    lastSeenDate: new Date('2024-01-18'),
    description: 'Gato siamês encontrado na rua, parece estar perdido. Está bem cuidado.',
    photoUrl: '/siamese-cat.png',
    contactPhone: '+5511965432109',
    contactName: 'Ana Costa',
    sightings: [],
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    userId: '1',
    status: 'adoption',
    name: 'Luna',
    type: 'cat',
    breed: 'Vira-lata',
    size: 'small',
    age: '1 ano',
    location: {
      lat: -23.5435,
      lng: -46.6395,
      address: 'Bela Vista',
      city: 'São Paulo',
      neighborhood: 'Bela Vista',
    },
    lastSeenDate: new Date('2024-01-10'),
    description: 'Gatinha muito carinhosa, castrada e vacinada. Procura um lar amoroso.',
    photoUrl: '/cute-white-cat.jpg',
    contactPhone: '+5511987654321',
    contactName: 'João Silva',
    sightings: [],
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '4',
    userId: '3',
    status: 'lost',
    name: 'Mel',
    type: 'dog',
    breed: 'Shih Tzu',
    size: 'small',
    age: '5 anos',
    location: {
      lat: -23.5745,
      lng: -46.6234,
      address: 'Vila Mariana',
      city: 'São Paulo',
      neighborhood: 'Vila Mariana',
    },
    lastSeenDate: new Date('2024-01-20'),
    description: 'Cachorrinha pequena, pelo longo marrom e branco. Muito dócil.',
    photoUrl: '/fluffy-shih-tzu.png',
    reward: 300,
    contactPhone: '+5511954321098',
    contactName: 'Carlos Oliveira',
    sightings: [],
    createdAt: new Date('2024-01-20'),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    userId: '1',
    type: 'sighting',
    petId: '1',
    title: 'Novo avistamento de Rex',
    message: 'Seu pet foi avistado na Rua Augusta',
    read: false,
    createdAt: new Date('2024-01-16'),
    sighting: mockPets[0].sightings[0],
  },
  {
    id: 'n2',
    userId: '1',
    type: 'nearby',
    petId: '2',
    title: 'Pet encontrado próximo a você',
    message: 'Um gato siamês foi encontrado perto da sua localização',
    read: false,
    createdAt: new Date('2024-01-18'),
  },
]
